import os
import time
def aaa():
    os.system("title System")
    os.system("clear")
    print("⠲⠤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⣸⡏⠀⠉⠳⢄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⣿⠀⠀⠀⠀⠀⠀⠀⠉⠲⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⢰⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠲⣄⠀⠀⠀⡰⠋⢙⣿⣦⡀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print(" ⠸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣙⣦⣮⣤⡀⣸⣿⣿⣿⣆⠀⠀⠀⠀")
    time.sleep(0.05)
    print(" ⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⣿⢟⣫⠟⠋⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣷⣷⣿⡁⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⢸⣿⣿⣧⣿⣿⣆⠙⢆⡀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢾⣿⣤⣿⣿⣿⡟⠹⣿⣿⣿⣿⣷⡀⠀⠀")

    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣧⣴⣿⣿⣿⣿⠏⢧⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠈⢳⡀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡏⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⢳")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠸⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡇⢠⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠃⢸⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣼⢸⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀")
    time.sleep(0.05)
    print("⠀⠀⠀⠀⠀⠀⠀⠛⠻⠿⣿⣿⣿⡿⠿⠿⠿⠿⠿⢿⣿⣿⠏⠀")
    time.sleep(0.05)
    print("")
    print("")
    print("   ___   ____    ____  _______  ____  ____   ___   ____    ____  _______  ")
    time.sleep(0.05)
    print(" .'   `.|_   \  /   _||  ___  ||_  _||_  _|.'   `.|_   \  /   _||  ___  |")
    time.sleep(0.05)
    print("/  .-.  \ |   \/   |  |_/  / /   \ \  / / /  .-.  \ |   \/   |  |_/  / /")
    time.sleep(0.05)
    print("| |   | | | |\  /| |      / /     > `' <  | |   | | | |\  /| |      / /")
    time.sleep(0.05)
    print("\  `-'  /_| |_\/_| |_    / /    _/ /'`\ \_\  `-'  /_| |_\/_| |_    / /")
    time.sleep(0.05)
    print(" `.___.'|_____||_____|  /_/    |____||____|`.___.'|_____||_____|  /_/")
    time.sleep(0.05)
    time.sleep(3)
    os.system("clear")
    print("⣿⣿⣿⣿⣿⣿⣿⣟⡁⣼⣿⣿⣿⣿⣷⠀⣿⣿⣿⣿⣿⣿⣿")
    print("⣿⣿⣿⣿⣿⣿⣿⠷⢔⣾⣿⣿⣿⣿⣿⣆⢴⢻⣿⣿⣿⣿⣿")
    print("⣿⣿⣿⣿⣿⣿⣯⢁⢽⣿⣿⣿⣿⣿⣿⣿⣦⡨⢻⣿⣿⣿⣿")
    print("⣿⣿⣿⣿⣿⣏⠇⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡃⠿⣿⣿⣿")
    print("⣿⣿⣿⣿⡏⢁⣴⣿⢿⠻⠿⠿⠻⠿⣟⠿⡿⣿⣾⣅⢏⣿⣿")
    print("⣿⣿⣿⡍⣡⡾⠋⠈⣀⣴⣾⣾⣿⣿⣶⣴⡀⠀⠹⠷⣧⡕⠻")
    print("⣿⢟⠅⢴⠂⠀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣾⢆⠀⠀⠘⡊⢆")
    print("⠑⢠⣶⠁⠀⣾⣿⣿⣿⣿⠟⢉⡉⠻⣿⣿⣿⢿⢥⠀⠀⠉⣾")
    print("⣴⣿⠁⠀⠀⣿⣿⣿⣿⣿⣄⡈⠁⣴⣿⣿⣿⣻⡏⠀⠀⠀⢽")
    print("⣿⡇⠀⣴⣦⣈⠻⢿⣿⣿⣿⣿⣿⣿⣿⡿⠏⠀⣠⠀⠀⠀⠀")
    print("⣿⠁⢸⣿⣿⣿⣾⡢⡀⠋⠻⠛⠟⠋⠁⣀⣴⣾⣗⠀⠀⠀⠀")
    print("⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣶⣶⣿⣿⣿⣿⡇⠀⠀⣴⠓")
    print("⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⡠⣴⣿⡇⠄")
    print("⡿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣫⣶⣷⣿⣿⣿⡇⣵")
    print("⣿⡿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣾⣿⣿⣿⣿⣿⣏⠐⣿")
    print("⣿⣵⣿⣻⣽⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⣶⣿")
    print("⡿⢻⣾⣿⣟⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡓⢰⣿⣿")
    print("⣿⣿⢟⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⣩⣿⠇⢠⣿⣿⣿")
    print("⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⢿⠋⢁⣰⣿⣿⡋⢠⣿⣿⣿⣿")
    print("⣿⣿⣿⣿⣿⣿⣿⠿⡛⠉⠀⣀⣶⣿⣿⣿⠃⢴⣿⣿⣿⣿⣿")
    print("⡻⠻⠛⠟⠉⠉⠀⠀⢀⣠⣶⣿⣿⣿⣿⠋⣲⣿⣿⣿⣿⣿⣿")
    print("⠀⠀⠀⠀⢀⡀⣠⣶⣾⣿⣿⣿⣿⣿⢃⣾⣿⣿⣿⣿⣿⣿⣿")
    time.sleep(0.5)
    print("Welcome from the adb commands communitey.")
    time.sleep(3)
    os.system("clear")
    print("    ▄▄▄▄     ▄▄▄▄    ▄▄▄  ▄▄▄  ▄▄▄  ▄▄▄     ▄▄     ▄▄▄   ▄▄  ▄▄▄▄▄       ▄▄▄▄   ")
    print("  ██▀▀▀▀█   ██▀▀██   ███  ███  ███  ███    ████    ███   ██  ██▀▀▀██   ▄█▀▀▀▀█  ")
    print(" ██▀       ██    ██  ████████  ████████    ████    ██▀█  ██  ██    ██  ██▄      ")
    print(" ██        ██    ██  ██ ██ ██  ██ ██ ██   ██  ██   ██ ██ ██  ██    ██   ▀████▄  ")
    print(" ██▄       ██    ██  ██ ▀▀ ██  ██ ▀▀ ██   ██████   ██  █▄██  ██    ██       ▀██ ")
    print("  ██▄▄▄▄█   ██▄▄██   ██    ██  ██    ██  ▄██  ██▄  ██   ███  ██▄▄▄██   █▄▄▄▄▄█▀ ")
    print("    ▀▀▀▀     ▀▀▀▀    ▀▀    ▀▀  ▀▀    ▀▀  ▀▀    ▀▀  ▀▀   ▀▀▀  ▀▀▀▀▀      ▀▀▀▀▀   ")
    print("")
    print("")
    print("1   :   ADB Commands")
    print("2   :   Remote ADB commands")
    choise = input('Number = ')
    if choise == "1":
        print("wich command will you like to run?")
        choise2 = input("command = ")
        if choise2 == "":
            time.sleep(0.5)
            os.system(choise2)
    if choise == "2":
        os.system("clear")
        print("  :####:   ########  ######:   ##:  :##  ########  ######:  ")
        print(" :######   ########  #######   ##    ##  ########  #######  ")
        print(" ##:  :#   ##        ##   :##  :##  ##:  ##        ##   :## ")
        print(" ##        ##        ##    ##  :##  ##:  ##        ##    ## ")
        print(" ###:      ##        ##   :##   ## .##   ##        ##   :## ")
        print(" :#####:   #######   #######:   ##::##   #######   #######: ")
        print("  .#####:  #######   ######     ##::##   #######   ######   ")
        print("     :###  ##        ##   ##.   :####:   ##        ##   ##. ")
        print("       ##  ##        ##   ##    .####.   ##        ##   ##  ")
        print(" #:.  :##  ##        ##   :##    ####    ##        ##   :## ")
        print(" #######:  ########  ##    ##:   ####    ########  ##    ##:")
        print(" .#####:   ########  ##    ###    ##     ########  ##    ###")
        print("")
        print("")
        print("Enter an IP You would like to run ADB commands on.")
        choise3 = input("IP = ")
        if choise3 == "83.250.89.112":
            os.system("clear")
            print("Sending request to remote server...")
            time.sleep(0.5)
            print("Port found 1 HOST up")
            time.sleep(0.5)
            print("Accesing..")
            time.sleep(0.5)
            print('"Acces denied."')
            time.sleep(0.5)
            print("Retrying..")
            time.sleep(0.1)
            print("Retrying(2)")
            time.sleep(0.1)
            print("Retrying(3)")
            time.sleep(0.1)
            print("Retrying(4)")
            time.sleep(0.1)
            print("Retrying(5)")
            time.sleep(1)
            print("Running as admin")
            time.sleep(0.5)
            print("Succsfly got acces to port")
            time.sleep(0.1)

            print('Succesfly connected ADB commands to "83.250.89.112"')
            time.sleep(1)
            time.sleep(1)
            os.system("clear")
            print("⠀⠀⠀⠀⣀⠤⠔⠒⠒⠒⠒⠒⠒⠒⠦⢄⣀⠀⠀⠀⠀")
            print("⠀⢀⡴⠋⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠈⠑⢄⠀⠀")
            print("⢀⠎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⠈⢣⠀")
            print("⢸⠀⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⢢⠈⡇")
            print("⢸⠀⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⡼⠀⡇")
            print("⠘⡆⢸⠀⢀⣀⣤⣄⡀⠀⠀   ⠀⢀⣤⣤⣄⡀⠀⡇⡸⠀")
            print("⠀⠘⣾⠀⣿ ⣿⣿⣿⣿⠀   ⠀⠀⣿⣿⣿⣿⣿⠀⡗⠁⠀")
            print("⠀⠀⣿⠀⠙⢿⣿⠿⠃⢠   ⢠⡀⠙⠿⣿⠿⠃⠀⡇⠀⠀")
            print("⠀⠀⠘⣄⡀⠀⠀⠀⢠⣿   ⢸⣿⠀⠀⠀⠀⠀⣠⠇⠀⠀")
            print("⠀⠀⠀⠀⡏⢷⡄⠀⠘⠟⠈⠿   ⠁⠀⢠⡞⡹⠁⠀")
            print("⠀⠀⠀⠀⢹⠸⠘⢢ ⢠⠤⠤  ⡤⡄⢰⢡⠁⡇⠀⠀⠀")
            print("⠀⠀⠀⠀⢸⠀⠣⣹⢸⠒   ⠒⡗⡇⣩⠌⢀⡇⠀⠀⠀")
            print("⠀⠀⠀⠀⠈⢧⡀⠀⠉   ⠉⠉⠉⠁⠀⣀⠜⠀⠀⠀⠀")
            print("⠀⠀⠀⠀⠀⠀⠉⠓⠢⠤⠤   ⠤⠔⠊⠁⠀⠀⠀⠀")
            print("")
            print("")

            print('What command will you like to run?')
            choise4 = input("command = ")
            time.sleep(1)
            os.system("clear")
            print("[x] Got the root file")
            time.sleep(0.1)
            print('[x] starting scan')
            time.sleep(0.1)
            print("found 3 keys")
            time.sleep(0.1)
            print('sudo apt open-cv python')
            time.sleep(0.1)
            print('ROOT R/')
            time.sleep(0.1)
            print('ROOT C/')
            time.sleep(0.1)
            print('ROOT O/')
            time.sleep(0.1)
            print('Giving access to root file')
            time.sleep(2)
            print('Running command')
            time.sleep(2)
            print('"pauseing"')
            time.sleep(0.1)
            print("pkg update")
            time.sleep(0.1)
            print("root/2")
            time.sleep(0.1)
            print("taskkill /F /IM svchost.exe/f")
            time.sleep(0.1)
            print("taskman-2")
            time.sleep(0.1)
            print("starting nmap scan for more wifi ports")
            time.sleep(0.1)
            print('error - "Access denied"')
            time.sleep(0.1)
            print("Retrying scan-network (1)")
            time.sleep(0.1)
            print("Retrying scan-network (2)")
            time.sleep(0.1)
            print("Retrying scan-network (3)")
            time.sleep(0.1)
            print("Retrying scan-network (4)")
            time.sleep(0.1)
            print("Succesfly scanning..")
            time.sleep(0.1)
            print("Scanning -'WIFI/2'")
            time.sleep(0.1)
            print("[x] NEW NETWORK (1)")
            time.sleep(0.1)
            print("[x] NEW NETWORK (2)")
            time.sleep(0.1)
            print("Giving The curret IP accses to target IP")
            time.sleep(0.1)
            print('[x] transforming "WIFI-1"')
            time.sleep(0.1)
            print('[x] transforming "Acces Firewall"')
            time.sleep(0.1)
            print("Scan Firewall")
            time.sleep(0.1)
            print("Succseful Acces has been given.")
            time.sleep(0.1)
            print("Ready.")

            time.sleep(2)
            os.system("clear")
            print("Send command to server?")
            print("(y/n)")
            choise0 = input("awnser = ")
            if choise0 == "y":
                print("Command is being executed.")
                time.sleep(0.5)
                print("Executed!")
                time.sleep(2)
                os.system("clear")
                time.sleep(2)
                aaa()
            if choise0 == "n":
                print("Command is Termed.")
                time.sleep(999)

os.system("title System")
os.system("color 4")
os.system("clear")
print("⠲⠤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⣸⡏⠀⠉⠳⢄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⣿⠀⠀⠀⠀⠀⠀⠀⠉⠲⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⢰⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠲⣄⠀⠀⠀⡰⠋⢙⣿⣦⡀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print(" ⠸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣙⣦⣮⣤⡀⣸⣿⣿⣿⣆⠀⠀⠀⠀")
time.sleep(0.05)
print(" ⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⠀⣿⢟⣫⠟⠋⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⣿⣿⣿⣿⣷⣷⣿⡁⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⢸⣿⣿⣧⣿⣿⣆⠙⢆⡀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢾⣿⣤⣿⣿⣿⡟⠹⣿⣿⣿⣿⣷⡀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣧⣴⣿⣿⣿⣿⠏⢧⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠈⢳⡀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡏⣸⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⠀⠀⢳")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠸⣿⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡇⢠⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠃⢸⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣼⢸⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀")
time.sleep(0.05)
print("⠀⠀⠀⠀⠀⠀⠀⠛⠻⠿⣿⣿⣿⡿⠿⠿⠿⠿⠿⢿⣿⣿⠏⠀")
time.sleep(0.05)
print("")
print("")
print("   ___   ____    ____  _______  ____  ____   ___   ____    ____  _______  ")
time.sleep(0.05)
print(" .'   `.|_   \  /   _||  ___  ||_  _||_  _|.'   `.|_   \  /   _||  ___  |")
time.sleep(0.05)
print("/  .-.  \ |   \/   |  |_/  / /   \ \  / / /  .-.  \ |   \/   |  |_/  / /")
time.sleep(0.05)
print("| |   | | | |\  /| |      / /     > `' <  | |   | | | |\  /| |      / /")
time.sleep(0.05)
print("\  `-'  /_| |_\/_| |_    / /    _/ /'`\ \_\  `-'  /_| |_\/_| |_    / /")
time.sleep(0.05)
print(" `.___.'|_____||_____|  /_/    |____||____|`.___.'|_____||_____|  /_/")
time.sleep(0.05)
time.sleep(3)
os.system("clear")
print("⣿⣿⣿⣿⣿⣿⣿⣟⡁⣼⣿⣿⣿⣿⣷⠀⣿⣿⣿⣿⣿⣿⣿")
print("⣿⣿⣿⣿⣿⣿⣿⠷⢔⣾⣿⣿⣿⣿⣿⣆⢴⢻⣿⣿⣿⣿⣿")
print("⣿⣿⣿⣿⣿⣿⣯⢁⢽⣿⣿⣿⣿⣿⣿⣿⣦⡨⢻⣿⣿⣿⣿")
print("⣿⣿⣿⣿⣿⣏⠇⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡃⠿⣿⣿⣿")
print("⣿⣿⣿⣿⡏⢁⣴⣿⢿⠻⠿⠿⠻⠿⣟⠿⡿⣿⣾⣅⢏⣿⣿")
print("⣿⣿⣿⡍⣡⡾⠋⠈⣀⣴⣾⣾⣿⣿⣶⣴⡀⠀⠹⠷⣧⡕⠻")
print("⣿⢟⠅⢴⠂⠀⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿⣾⢆⠀⠀⠘⡊⢆")
print("⠑⢠⣶⠁⠀⣾⣿⣿⣿⣿⠟⢉⡉⠻⣿⣿⣿⢿⢥⠀⠀⠉⣾")
print("⣴⣿⠁⠀⠀⣿⣿⣿⣿⣿⣄⡈⠁⣴⣿⣿⣿⣻⡏⠀⠀⠀⢽")
print("⣿⡇⠀⣴⣦⣈⠻⢿⣿⣿⣿⣿⣿⣿⣿⡿⠏⠀⣠⠀⠀⠀⠀")
print("⣿⠁⢸⣿⣿⣿⣾⡢⡀⠋⠻⠛⠟⠋⠁⣀⣴⣾⣗⠀⠀⠀⠀")
print("⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣶⣶⣿⣿⣿⣿⡇⠀⠀⣴⠓")
print("⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⡠⣴⣿⡇⠄")
print("⡿⣯⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣫⣶⣷⣿⣿⣿⡇⣵")
print("⣿⡿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣾⣿⣿⣿⣿⣿⣏⠐⣿")
print("⣿⣵⣿⣻⣽⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⣶⣿")
print("⡿⢻⣾⣿⣟⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡓⢰⣿⣿")
print("⣿⣿⢟⣷⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⣩⣿⠇⢠⣿⣿⣿")
print("⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⢿⠋⢁⣰⣿⣿⡋⢠⣿⣿⣿⣿")
print("⣿⣿⣿⣿⣿⣿⣿⠿⡛⠉⠀⣀⣶⣿⣿⣿⠃⢴⣿⣿⣿⣿⣿")
print("⡻⠻⠛⠟⠉⠉⠀⠀⢀⣠⣶⣿⣿⣿⣿⠋⣲⣿⣿⣿⣿⣿⣿")
print("⠀⠀⠀⠀⢀⡀⣠⣶⣾⣿⣿⣿⣿⣿⢃⣾⣿⣿⣿⣿⣿⣿⣿")
time.sleep(0.5)
print("Welcome from the adb commands communitey.")
time.sleep(3)
os.system("clear")
print("    ▄▄▄▄     ▄▄▄▄    ▄▄▄  ▄▄▄  ▄▄▄  ▄▄▄     ▄▄     ▄▄▄   ▄▄  ▄▄▄▄▄       ▄▄▄▄   ")
print("  ██▀▀▀▀█   ██▀▀██   ███  ███  ███  ███    ████    ███   ██  ██▀▀▀██   ▄█▀▀▀▀█  ")
print(" ██▀       ██    ██  ████████  ████████    ████    ██▀█  ██  ██    ██  ██▄      ")
print(" ██        ██    ██  ██ ██ ██  ██ ██ ██   ██  ██   ██ ██ ██  ██    ██   ▀████▄  ")
print(" ██▄       ██    ██  ██ ▀▀ ██  ██ ▀▀ ██   ██████   ██  █▄██  ██    ██       ▀██ ")
print("  ██▄▄▄▄█   ██▄▄██   ██    ██  ██    ██  ▄██  ██▄  ██   ███  ██▄▄▄██   █▄▄▄▄▄█▀ ")
print("    ▀▀▀▀     ▀▀▀▀    ▀▀    ▀▀  ▀▀    ▀▀  ▀▀    ▀▀  ▀▀   ▀▀▀  ▀▀▀▀▀      ▀▀▀▀▀   ")
print("")
print("")
print("1   :   ADB Commands")
print("2   :   Remote ADB commands")
choise = input('Number = ')
if choise == "1":
    print("wich command will you like to run?")
    choise2 = input("command = ")
    if choise2 == "":
        time.sleep(0.5)
        os.system(choise2)
if choise == "2":
    os.system("clear")
    print("  :####:   ########  ######:   ##:  :##  ########  ######:  ")
    print(" :######   ########  #######   ##    ##  ########  #######  ")
    print(" ##:  :#   ##        ##   :##  :##  ##:  ##        ##   :## ")
    print(" ##        ##        ##    ##  :##  ##:  ##        ##    ## ")
    print(" ###:      ##        ##   :##   ## .##   ##        ##   :## ")
    print(" :#####:   #######   #######:   ##::##   #######   #######: ")
    print("  .#####:  #######   ######     ##::##   #######   ######   ")
    print("     :###  ##        ##   ##.   :####:   ##        ##   ##. ")
    print("       ##  ##        ##   ##    .####.   ##        ##   ##  ")
    print(" #:.  :##  ##        ##   :##    ####    ##        ##   :## ")
    print(" #######:  ########  ##    ##:   ####    ########  ##    ##:")
    print(" .#####:   ########  ##    ###    ##     ########  ##    ###")
    print("")
    print("")
    print("Enter an IP You would like to run ADB commands on.")
    choise3 = input("IP = ")
    if choise3 == "01298348745765":
        print("hi")
    else:
        os.system("clear")
        print("Sending request to remote server...")
        time.sleep(0.5)
        print("Port found 1 HOST up")
        time.sleep(0.5)
        print("Accesing..")
        time.sleep(0.5)
        print('"Acces denied."')
        time.sleep(0.5)
        print("Retrying..")
        time.sleep(0.1)
        print("Retrying(2)")
        time.sleep(0.1)
        print("Retrying(3)")
        time.sleep(0.1)
        print("Retrying(4)")
        time.sleep(0.1)
        print("Retrying(5)")
        time.sleep(1)
        print("Running as admin")
        time.sleep(0.5)
        print("Succsfly got acces to port")
        time.sleep(0.1)

        print('Succesfly connected ADB commands to "83.250.89.112"')
        time.sleep(1)
        time.sleep(1)
        os.system("clear")
        print("⠀⠀⠀⠀⣀⠤⠔⠒⠒⠒⠒⠒⠒⠒⠦⢄⣀⠀⠀⠀⠀")
        print("⠀⢀⡴⠋⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠈⠑⢄⠀⠀")
        print("⢀⠎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⠈⢣⠀")
        print("⢸⠀⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⢢⠈⡇")
        print("⢸⠀⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⠀⠀⠀⡼⠀⡇")
        print("⠘⡆⢸⠀⢀⣀⣤⣄⡀⠀⠀   ⠀⢀⣤⣤⣄⡀⠀⡇⡸⠀")
        print("⠀⠘⣾⠀⣿ ⣿⣿⣿⣿⠀   ⠀⠀⣿⣿⣿⣿⣿⠀⡗⠁⠀")
        print("⠀⠀⣿⠀⠙⢿⣿⠿⠃⢠   ⢠⡀⠙⠿⣿⠿⠃⠀⡇⠀⠀")
        print("⠀⠀⠘⣄⡀⠀⠀⠀⢠⣿   ⢸⣿⠀⠀⠀⠀⠀⣠⠇⠀⠀")
        print("⠀⠀⠀⠀⡏⢷⡄⠀⠘⠟⠈⠿   ⠁⠀⢠⡞⡹⠁⠀")
        print("⠀⠀⠀⠀⢹⠸⠘⢢ ⢠⠤⠤  ⡤⡄⢰⢡⠁⡇⠀⠀⠀")
        print("⠀⠀⠀⠀⢸⠀⠣⣹⢸⠒   ⠒⡗⡇⣩⠌⢀⡇⠀⠀⠀")
        print("⠀⠀⠀⠀⠈⢧⡀⠀⠉   ⠉⠉⠉⠁⠀⣀⠜⠀⠀⠀⠀")
        print("⠀⠀⠀⠀⠀⠀⠉⠓⠢⠤⠤   ⠤⠔⠊⠁⠀⠀⠀⠀")
        print("")
        print("")

        print('What command will you like to run?')
        choise4 = input("command = ")
        time.sleep(1)
        os.system("clear")
        print("[x] Got the root file")
        time.sleep(0.1)
        print('[x] starting scan')
        time.sleep(0.1)
        print("found 3 keys")
        time.sleep(0.1)
        print('sudo apt open-cv python')
        time.sleep(0.1)
        print('ROOT R/')
        time.sleep(0.1)
        print('ROOT C/')
        time.sleep(0.1)
        print('ROOT O/')
        time.sleep(0.1)
        print('Giving access to root file')
        time.sleep(2)
        print('Running command')
        time.sleep(2)
        print('"pauseing"')
        time.sleep(0.1)
        print("pkg update")
        time.sleep(0.1)
        print("root/2")
        time.sleep(0.1)
        print("taskkill /F /IM svchost.exe/f")
        time.sleep(0.1)
        print("taskman-2")
        time.sleep(0.1)
        print("starting nmap scan for more wifi ports")
        time.sleep(0.1)
        print('error - "Access denied"')
        time.sleep(0.1)
        print("Retrying scan-network (1)")
        time.sleep(0.1)
        print("Retrying scan-network (2)")
        time.sleep(0.1)
        print("Retrying scan-network (3)")
        time.sleep(0.1)
        print("Retrying scan-network (4)")
        time.sleep(0.1)
        print("Succesfly scanning..")
        time.sleep(0.1)
        print("Scanning -'WIFI/2'")
        time.sleep(0.1)
        print("[x] NEW NETWORK (1)")
        time.sleep(0.1)
        print("[x] NEW NETWORK (2)")
        time.sleep(0.1)
        print("Giving The curret IP accses to target IP")
        time.sleep(0.1)
        print('[x] transforming "WIFI-1"')
        time.sleep(0.1)
        print('[x] transforming "Acces Firewall"')
        time.sleep(0.1)
        print("Scan Firewall")
        time.sleep(0.1)
        print("Succseful Acces has been given.")
        time.sleep(0.1)
        print("Ready.")



        time.sleep(2)
        os.system("clear")
        print("Send command to server?")
        print("(y/n)")
        choise0 = input("awnser = ")
        if choise0 == "y":
            print("Command is being executed.")
            time.sleep(0.5)
            print("Executed!")
            time.sleep(2)
            os.system("clear")
            time.sleep(2)
            aaa()
        if choise0 == "n":
            print("Command is Termed.")
            time.sleep(999)
