import os
import time
os.system("clear")
print("Hello.")
time.sleep(1)
print("This is just a test.")
time.sleep(3)
print("I will close this code soon")
time.sleep(2)
print("Just joking,I hacked Ur ass")
time.sleep(4)
print("00")
os.system("cmatrix")
time.sleep(1)
os.system("clear")